# Generated by Django 3.1.8 on 2021-06-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_business_rules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessrulemodel',
            name='creation_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessrulemodel',
            name='deleted_timestamp',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='businessrulemodel',
            name='updated_timestamp',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
